use std::fmt::Write as _;

pub const KMARK_PARAM_SCHEMA_VERSION: u32 = 15;

pub struct KmarkParamSpec {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub param_type: &'static str,
    pub contexts: &'static [&'static str],
    pub values: &'static [&'static str],
    pub insert_text: &'static str,
    pub description: &'static str,
    pub examples: &'static [&'static str],
    pub priority: u16,
}

pub const KMARK_PARAM_SPECS: &[KmarkParamSpec] = &[
    KmarkParamSpec {
        name: "align",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "scope", "text", "image", "model"],
        values: &["left", "center", "right"],
        insert_text: "align:",
        description: "対象ブロックの横方向配置を指定する",
        examples: &["<!-- kmark align:right -->"],
        priority: 100,
    },
    KmarkParamSpec {
        name: "valign",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "scope", "text", "image"],
        values: &["top", "center", "bottom", "stretch"],
        insert_text: "valign:",
        description: "対象ブロックの縦方向配置を指定する",
        examples: &["<!-- kmark valign:top -->"],
        priority: 70,
    },
    KmarkParamSpec {
        name: "page_valign",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "scope", "text", "image"],
        values: &["top", "center", "bottom"],
        insert_text: "page_valign:",
        description: "対象ブロックを現在ページの本文エリア内で縦配置する",
        examples: &["<!-- kmark page_valign:bottom -->"],
        priority: 88,
    },
    KmarkParamSpec {
        name: "toc",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "toc"],
        values: &[],
        insert_text: "toc:true",
        description: "現在位置以降の見出しから目次を生成する",
        examples: &["<!-- kmark toc:true -->"],
        priority: 110,
    },
    KmarkParamSpec {
        name: "toc_depth",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "toc"],
        values: &["1", "2", "3", "4", "5", "6"],
        insert_text: "toc_depth:",
        description: "目次へ表示する最大見出し深度を指定する",
        examples: &["<!-- kmark toc:true toc_depth:3 -->"],
        priority: 96,
    },
    KmarkParamSpec {
        name: "toc_min_depth",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "toc"],
        values: &["1", "2", "3", "4", "5", "6"],
        insert_text: "toc_min_depth:",
        description: "目次へ表示する最小見出し深度を指定する",
        examples: &["<!-- kmark toc:true toc_min_depth:2 toc_depth:4 -->"],
        priority: 82,
    },
    KmarkParamSpec {
        name: "toc_title",
        aliases: &[],
        param_type: "string",
        contexts: &["single", "toc"],
        values: &[],
        insert_text: "toc_title:\"目次\"",
        description: "目次タイトルを指定する。空文字で非表示にする",
        examples: &["<!-- kmark toc:true toc_title:\"Contents\" -->"],
        priority: 92,
    },
    KmarkParamSpec {
        name: "toc_ordered",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "toc"],
        values: &[],
        insert_text: "toc_ordered:",
        description: "目次を番号付きリストで表示する",
        examples: &["<!-- kmark toc:true toc_ordered:true -->"],
        priority: 78,
    },
    KmarkParamSpec {
        name: "toc_links",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "toc"],
        values: &[],
        insert_text: "toc_links:",
        description: "目次項目から見出しへのリンク有無を指定する",
        examples: &["<!-- kmark toc:true toc_links:false -->"],
        priority: 76,
    },
    KmarkParamSpec {
        name: "heading_number",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "scope"],
        values: &[],
        insert_text: "heading_number:true",
        description: "スコープ内の見出し番号表示を有効化する",
        examples: &["<!-- kmark heading_number:true -->"],
        priority: 109,
    },
    KmarkParamSpec {
        name: "heading_number_from",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "scope"],
        values: &["1", "2", "3", "4", "5", "6"],
        insert_text: "heading_number_from:",
        description: "番号付けを開始するMarkdown見出しレベルを指定する",
        examples: &["<!-- kmark heading_number:true heading_number_from:2 -->"],
        priority: 98,
    },
    KmarkParamSpec {
        name: "heading_number_depth",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "scope"],
        values: &["1", "2", "3", "4", "5", "6"],
        insert_text: "heading_number_depth:",
        description: "開始見出しレベルから番号表示する階層深度を指定する",
        examples: &["<!-- kmark heading_number:true heading_number_depth:3 -->"],
        priority: 97,
    },
    KmarkParamSpec {
        name: "heading_number_pattern",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "scope"],
        values: &["dot", "dot_trailing", "hyphen", "chapter"],
        insert_text: "heading_number_pattern:",
        description: "見出し番号の表示形式を指定する",
        examples: &["<!-- kmark heading_number:true heading_number_pattern:dot -->"],
        priority: 96,
    },
    KmarkParamSpec {
        name: "w",
        aliases: &["width"],
        param_type: "length",
        contexts: &["single", "scope", "text", "image", "model", "shape", "table"],
        values: &[],
        insert_text: "w:",
        description: "対象要素の幅を指定する。fitで内容幅、page_fitで現在位置からページ本文右端までの残幅、page_fit_containで縦横比維持の最大収まり幅に合わせる",
        examples: &[
            "<!-- kmark w:200 -->",
            "<!-- kmark w:fit -->",
            "<!-- kmark w:page_fit -->",
            "<!-- kmark w:page_fit_contain h:page_fit_contain -->",
        ],
        priority: 95,
    },
    KmarkParamSpec {
        name: "h",
        aliases: &["height"],
        param_type: "length",
        contexts: &["single", "scope", "text", "image", "model", "shape"],
        values: &[],
        insert_text: "h:",
        description: "対象要素の高さを指定する。fitで内容高、page_fitで現在位置からページ本文下端までの残高、page_fit_containで縦横比維持の最大収まり高に合わせる",
        examples: &[
            "<!-- kmark h:100 -->",
            "<!-- kmark h:fit -->",
            "<!-- kmark h:page_fit -->",
            "<!-- kmark w:page_fit_contain h:page_fit_contain -->",
        ],
        priority: 95,
    },
    KmarkParamSpec {
        name: "pos",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "image"],
        values: &[
            "center",
            "top",
            "bottom",
            "left",
            "right",
            "top_left",
            "top_right",
            "bottom_left",
            "bottom_right",
        ],
        insert_text: "pos:",
        description: "画像や要素内の表示位置を指定する",
        examples: &["<!-- kmark pos:top_left -->"],
        priority: 70,
    },
    KmarkParamSpec {
        name: "border_size",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "border_size:",
        description: "枠線の太さを指定する",
        examples: &["<!-- kmark border_size:2 -->"],
        priority: 80,
    },
    KmarkParamSpec {
        name: "border_color",
        aliases: &[],
        param_type: "color",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "border_color:",
        description: "枠線の色を指定する",
        examples: &[
            "<!-- kmark border_color:red -->",
            "<!-- kmark border_color:#ff0000 -->",
        ],
        priority: 80,
    },
    KmarkParamSpec {
        name: "border_style",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "image", "scope", "shape"],
        values: &["solid", "dashed", "dotted", "double", "none"],
        insert_text: "border_style:",
        description: "枠線の種類を指定する",
        examples: &["<!-- kmark border_style:dashed -->"],
        priority: 75,
    },
    KmarkParamSpec {
        name: "radius",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "radius:",
        description: "対象要素の角丸を指定する",
        examples: &["<!-- kmark radius:4px -->"],
        priority: 76,
    },
    KmarkParamSpec {
        name: "bg",
        aliases: &["background"],
        param_type: "color",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "bg:",
        description: "対象要素の背景色を指定する",
        examples: &["<!-- kmark bg:#fff0f0 -->"],
        priority: 74,
    },
    KmarkParamSpec {
        name: "background",
        aliases: &["bg"],
        param_type: "color",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "background:",
        description: "対象要素の背景色を指定する",
        examples: &["<!-- kmark background:#fff0f0 -->"],
        priority: 73,
    },
    KmarkParamSpec {
        name: "opacity",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "opacity:",
        description: "対象要素の透明度を0から1で指定する",
        examples: &["<!-- kmark opacity:0.8 -->"],
        priority: 72,
    },
    KmarkParamSpec {
        name: "rotate",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "rotate:",
        description: "対象要素の回転角度を指定する",
        examples: &["<!-- kmark rotate:-10 -->"],
        priority: 72,
    },
    KmarkParamSpec {
        name: "shadow",
        aliases: &[],
        param_type: "string",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "shadow:",
        description: "対象要素の影を指定する",
        examples: &["<!-- kmark shadow:true -->", "<!-- kmark shadow:sm -->"],
        priority: 71,
    },
    KmarkParamSpec {
        name: "margin",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "image", "scope", "shape", "table"],
        values: &[],
        insert_text: "margin:",
        description: "対象要素の外側余白を指定する",
        examples: &["<!-- kmark margin:2mm -->"],
        priority: 70,
    },
    KmarkParamSpec {
        name: "padding",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "image", "scope", "shape"],
        values: &[],
        insert_text: "padding:",
        description: "対象要素の内側余白を指定する",
        examples: &["<!-- kmark padding:2mm 4mm -->"],
        priority: 70,
    },
    KmarkParamSpec {
        name: "video_autoplay",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "video"],
        values: &[],
        insert_text: "video_autoplay:true",
        description: "動画を自動再生する",
        examples: &["<!-- kmark video_autoplay:true video_muted:true -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "video_muted",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "video"],
        values: &[],
        insert_text: "video_muted:true",
        description: "動画をミュート状態で開始する",
        examples: &["<!-- kmark video_muted:true -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "video_loop",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "video"],
        values: &[],
        insert_text: "video_loop:true",
        description: "動画をループ再生する",
        examples: &["<!-- kmark video_loop:true -->"],
        priority: 82,
    },
    KmarkParamSpec {
        name: "video_poster",
        aliases: &[],
        param_type: "string",
        contexts: &["single", "video"],
        values: &[],
        insert_text: "video_poster:",
        description: "動画の再生前に表示するサムネイル画像を指定する",
        examples: &["<!-- kmark video_poster:./thumb.png -->"],
        priority: 81,
    },
    KmarkParamSpec {
        name: "video_poster_time",
        aliases: &[],
        param_type: "string",
        contexts: &["single", "video"],
        values: &[],
        insert_text: "video_poster_time:",
        description: "poster画像未指定時に動画サムネイルとして表示する再生位置を指定する",
        examples: &["<!-- kmark video_poster_time:5s -->"],
        priority: 80,
    },
    KmarkParamSpec {
        name: "model_view",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "model"],
        values: &["front", "back", "left", "right", "top", "bottom", "iso"],
        insert_text: "model_view:",
        description: "3Dモデルの基本カメラ方向を指定する",
        examples: &["<!-- kmark model_view:iso -->"],
        priority: 95,
    },
    KmarkParamSpec {
        name: "model_projection",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "model"],
        values: &["perspective", "orthographic"],
        insert_text: "model_projection:",
        description: "3Dモデルの投影方式を指定する",
        examples: &["<!-- kmark model_projection:perspective -->"],
        priority: 94,
    },
    KmarkParamSpec {
        name: "model_fov",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "model"],
        values: &["25", "35", "45", "55", "60"],
        insert_text: "model_fov:",
        description: "透視投影時の視野角を指定する 25-60度へ制限する",
        examples: &["<!-- kmark model_fov:45 -->"],
        priority: 93,
    },
    KmarkParamSpec {
        name: "model_camera_yaw",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "model"],
        values: &[],
        insert_text: "model_camera_yaw:",
        description: "3Dモデルカメラの水平角度を指定する",
        examples: &["<!-- kmark model_camera_yaw:45 -->"],
        priority: 92,
    },
    KmarkParamSpec {
        name: "model_camera_pitch",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "model"],
        values: &[],
        insert_text: "model_camera_pitch:",
        description: "3Dモデルカメラの上下角度を指定する",
        examples: &["<!-- kmark model_camera_pitch:25 -->"],
        priority: 91,
    },
    KmarkParamSpec {
        name: "model_camera_distance",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "model"],
        values: &[],
        insert_text: "model_camera_distance:",
        description: "3Dモデル中心からカメラまでの距離を指定する",
        examples: &["<!-- kmark model_camera_distance:3 -->"],
        priority: 90,
    },
    KmarkParamSpec {
        name: "model_light_preset",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "model"],
        values: &["default", "studio", "flat", "product", "none"],
        insert_text: "model_light_preset:",
        description: "3Dモデル照明presetを指定する",
        examples: &["<!-- kmark model_light_preset:studio -->"],
        priority: 89,
    },
    KmarkParamSpec {
        name: "model_controls",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "model"],
        values: &[],
        insert_text: "model_controls:",
        description: "3Dモデル操作可否を指定する",
        examples: &["<!-- kmark model_controls:false -->"],
        priority: 88,
    },
    KmarkParamSpec {
        name: "model_auto_rotate",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "model"],
        values: &[],
        insert_text: "model_auto_rotate:true",
        description: "3Dモデルの自動回転を有効化する",
        examples: &["<!-- kmark model_auto_rotate:true -->"],
        priority: 87,
    },
    KmarkParamSpec {
        name: "model_bg",
        aliases: &[],
        param_type: "color",
        contexts: &["single", "model"],
        values: &["transparent"],
        insert_text: "model_bg:",
        description: "3Dモデルviewer背景色を指定する",
        examples: &["<!-- kmark model_bg:#f5f5f5 -->"],
        priority: 86,
    },
    KmarkParamSpec {
        name: "model_loading",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "model"],
        values: &["lazy", "eager"],
        insert_text: "model_loading:",
        description: "3Dモデル読み込み方式を指定する",
        examples: &["<!-- kmark model_loading:lazy -->"],
        priority: 85,
    },
    KmarkParamSpec {
        name: "model_convert",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "model"],
        values: &["auto", "never", "force"],
        insert_text: "model_convert:",
        description: "GLB変換制御を指定する",
        examples: &["<!-- kmark model_convert:auto -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "model_convert_force",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "model"],
        values: &[],
        insert_text: "model_convert_force:",
        description: "3DモデルGLB変換を強制する",
        examples: &["<!-- kmark model_convert_force:true -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "model_convert_scale",
        aliases: &[],
        param_type: "number",
        contexts: &["single", "model"],
        values: &["0.01", "0.1", "1", "10"],
        insert_text: "model_convert_scale:",
        description: "3Dモデル変換時倍率を指定する",
        examples: &["<!-- kmark model_convert_scale:0.01 -->"],
        priority: 82,
    },
    KmarkParamSpec {
        name: "model_convert_up",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "model"],
        values: &["z", "auto", "x", "y", "-x", "-y", "-z"],
        insert_text: "model_convert_up:",
        description: "3Dモデル変換時の入力上方向軸を指定する Z軸を表示上下に写像する",
        examples: &["<!-- kmark model_convert_up:z -->"],
        priority: 81,
    },
    KmarkParamSpec {
        name: "model_convert_center",
        aliases: &[],
        param_type: "boolean",
        contexts: &["single", "model"],
        values: &[],
        insert_text: "model_convert_center:",
        description: "3Dモデル変換時に中心補正する",
        examples: &["<!-- kmark model_convert_center:true -->"],
        priority: 80,
    },
    KmarkParamSpec {
        name: "color",
        aliases: &[],
        param_type: "color",
        contexts: &["single", "text", "scope"],
        values: &[],
        insert_text: "color:",
        description: "文字色を指定する",
        examples: &["<!-- kmark color:red -->\n重要"],
        priority: 78,
    },
    KmarkParamSpec {
        name: "font_weight",
        aliases: &[],
        param_type: "string",
        contexts: &["single", "text", "scope"],
        values: &[
            "normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700",
            "800", "900",
        ],
        insert_text: "font_weight:",
        description: "文字の太さを指定する",
        examples: &["<!-- kmark font_weight:bold -->\n承認済"],
        priority: 77,
    },
    KmarkParamSpec {
        name: "font_family",
        aliases: &[],
        param_type: "string",
        contexts: &["single", "text", "scope"],
        values: &[],
        insert_text: "font_family:",
        description: "文字のfont familyを指定する",
        examples: &["<!-- kmark font_family:\"Yu Gothic\" -->\n社外秘"],
        priority: 76,
    },
    KmarkParamSpec {
        name: "font_style",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "text", "scope"],
        values: &["normal", "italic", "oblique"],
        insert_text: "font_style:",
        description: "文字styleを指定する",
        examples: &["<!-- kmark font_style:italic -->\nDRAFT"],
        priority: 75,
    },
    KmarkParamSpec {
        name: "letter_spacing",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "text", "scope"],
        values: &[],
        insert_text: "letter_spacing:",
        description: "文字間隔を指定する",
        examples: &["<!-- kmark letter_spacing:0.08em -->\nCONFIDENTIAL"],
        priority: 74,
    },
    KmarkParamSpec {
        name: "line_height",
        aliases: &[],
        param_type: "string",
        contexts: &["single", "text", "scope", "table"],
        values: &[],
        insert_text: "line_height:",
        description: "行高を指定する",
        examples: &["<!-- kmark line_height:1.2 -->\n承認済"],
        priority: 73,
    },
    KmarkParamSpec {
        name: "table_cell_padding",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "scope", "table"],
        values: &[],
        insert_text: "table_cell_padding:",
        description: "表セルの内側余白を縦横まとめて指定する",
        examples: &["<!-- kmark table_cell_padding:0.3mm 1mm -->"],
        priority: 88,
    },
    KmarkParamSpec {
        name: "table_cell_padding_x",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "scope", "table"],
        values: &[],
        insert_text: "table_cell_padding_x:",
        description: "表セルの左右内側余白を指定する",
        examples: &["<!-- kmark table_cell_padding_x:1mm -->"],
        priority: 87,
    },
    KmarkParamSpec {
        name: "table_cell_padding_y",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "scope", "table"],
        values: &[],
        insert_text: "table_cell_padding_y:",
        description: "表セルの上下内側余白を指定する",
        examples: &["<!-- kmark table_cell_padding_y:0.3mm -->"],
        priority: 86,
    },
    KmarkParamSpec {
        name: "table_fit",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "scope", "table"],
        values: &["auto", "off", "shrink"],
        insert_text: "table_fit:",
        description: "表の用紙幅超過時の自動縮小方法を指定する",
        examples: &["<!-- kmark table_fit:shrink -->"],
        priority: 85,
    },
    KmarkParamSpec {
        name: "table_layout",
        aliases: &[],
        param_type: "enum",
        contexts: &["single", "scope", "table"],
        values: &["auto", "fixed"],
        insert_text: "table_layout:",
        description: "表の列幅計算方法を指定する",
        examples: &["<!-- kmark table_layout:fixed -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "layout",
        aliases: &[],
        param_type: "enum",
        contexts: &["scope"],
        values: &["row", "column"],
        insert_text: "layout:",
        description: "スコープ内の要素配置を指定する",
        examples: &["<!-- kmark { layout:row } -->"],
        priority: 100,
    },
    KmarkParamSpec {
        name: "gap",
        aliases: &[],
        param_type: "length",
        contexts: &["scope"],
        values: &[],
        insert_text: "gap:",
        description: "スコープ内の要素間隔を指定する",
        examples: &["<!-- kmark { layout:row gap:8 } -->"],
        priority: 85,
    },
    KmarkParamSpec {
        name: "wrap",
        aliases: &[],
        param_type: "boolean",
        contexts: &["scope"],
        values: &[],
        insert_text: "wrap:",
        description: "横並び要素の折り返しを有効にする",
        examples: &["<!-- kmark { layout:row wrap:true } -->"],
        priority: 80,
    },
    KmarkParamSpec {
        name: "page_size",
        aliases: &[],
        param_type: "enum",
        contexts: &["page", "scope"],
        values: &["A3", "A4", "A5", "B4", "B5", "Letter", "Legal", "custom"],
        insert_text: "page_size:",
        description: "ページサイズを指定する",
        examples: &["<!-- kmark { page_size:A4 } -->"],
        priority: 100,
    },
    KmarkParamSpec {
        name: "orientation",
        aliases: &["page_orientation"],
        param_type: "enum",
        contexts: &["page", "scope"],
        values: &["portrait", "landscape"],
        insert_text: "orientation:",
        description: "ページの向きを指定する",
        examples: &["<!-- kmark { orientation:landscape } -->"],
        priority: 95,
    },
    KmarkParamSpec {
        name: "page_width",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_width:",
        description: "customページの幅を指定する",
        examples: &["<!-- kmark { page_size:custom page_width:210mm } -->"],
        priority: 60,
    },
    KmarkParamSpec {
        name: "page_height",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_height:",
        description: "customページの高さを指定する",
        examples: &["<!-- kmark { page_size:custom page_height:297mm } -->"],
        priority: 60,
    },
    KmarkParamSpec {
        name: "font_size",
        aliases: &[],
        param_type: "length",
        contexts: &["single", "text", "scope", "table"],
        values: &[],
        insert_text: "font_size:",
        description: "文字装飾の文字サイズを指定する",
        examples: &[
            "<!-- kmark font_size:12pt -->\n重要",
            "<!-- kmark { font_size:12pt } -->",
        ],
        priority: 80,
    },
    KmarkParamSpec {
        name: "page_font_size",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_font_size:",
        description: "用紙表示全体の基準文字サイズを指定する",
        examples: &["<!-- kmark { page_font_size:12pt } -->"],
        priority: 79,
    },
    KmarkParamSpec {
        name: "page_font_family",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_font_family:",
        description: "用紙表示全体の本文font familyを指定する",
        examples: &["<!-- kmark { page_font_family:\"Yu Gothic\" } -->"],
        priority: 78,
    },
    KmarkParamSpec {
        name: "page_heading_font_family",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_heading_font_family:",
        description: "用紙表示全体の見出しfont familyを指定する",
        examples: &["<!-- kmark { page_heading_font_family:\"Noto Serif JP\" } -->"],
        priority: 77,
    },
    KmarkParamSpec {
        name: "page_margin",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_margin:",
        description: "用紙表示の余白を指定する",
        examples: &["<!-- kmark { page_margin:10mm } -->"],
        priority: 75,
    },
    KmarkParamSpec {
        name: "page_margin_top",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_margin_top:",
        description: "用紙表示の上余白を指定する",
        examples: &["<!-- kmark { page_margin_top:10mm } -->"],
        priority: 55,
    },
    KmarkParamSpec {
        name: "page_margin_right",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_margin_right:",
        description: "用紙表示の右余白を指定する",
        examples: &["<!-- kmark { page_margin_right:10mm } -->"],
        priority: 55,
    },
    KmarkParamSpec {
        name: "page_margin_bottom",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_margin_bottom:",
        description: "用紙表示の下余白を指定する",
        examples: &["<!-- kmark { page_margin_bottom:10mm } -->"],
        priority: 55,
    },
    KmarkParamSpec {
        name: "page_margin_left",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_margin_left:",
        description: "用紙表示の左余白を指定する",
        examples: &["<!-- kmark { page_margin_left:10mm } -->"],
        priority: 55,
    },
    KmarkParamSpec {
        name: "page_header",
        aliases: &[],
        param_type: "boolean",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header:false",
        description: "ページヘッダーの表示を無効化する",
        examples: &["<!-- kmark page_header:false -->"],
        priority: 89,
    },
    KmarkParamSpec {
        name: "page_header_left",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_left:\"\"",
        description: "ページヘッダー左端の文字列を指定する",
        examples: &["<!-- kmark page_header_left:\"左ヘッダー\" -->"],
        priority: 88,
    },
    KmarkParamSpec {
        name: "page_header_center",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_center:\"\"",
        description: "ページヘッダー中央の文字列を指定する",
        examples: &["<!-- kmark page_header_center:\"社外秘\" -->"],
        priority: 88,
    },
    KmarkParamSpec {
        name: "page_header_right",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_right:\"\"",
        description: "ページヘッダー右端の文字列を指定する",
        examples: &["<!-- kmark page_header_right:\"右ヘッダー\" -->"],
        priority: 88,
    },
    KmarkParamSpec {
        name: "page_header_opacity",
        aliases: &[],
        param_type: "number",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_opacity:",
        description: "ページヘッダーの透明度を0から1で指定する",
        examples: &["<!-- kmark page_header_opacity:0.6 -->"],
        priority: 86,
    },
    KmarkParamSpec {
        name: "page_header_offset",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_offset:",
        description: "ページ上端からヘッダーまでの距離を指定する",
        examples: &["<!-- kmark page_header_offset:6mm -->"],
        priority: 86,
    },
    KmarkParamSpec {
        name: "page_header_border_size",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_border_size:",
        description: "ページヘッダーの枠線太さを指定する",
        examples: &["<!-- kmark page_header_border_size:1px -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_header_border_color",
        aliases: &[],
        param_type: "color",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_border_color:",
        description: "ページヘッダーの枠線色を指定する",
        examples: &["<!-- kmark page_header_border_color:#999 -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_header_border_style",
        aliases: &[],
        param_type: "enum",
        contexts: &["page", "scope"],
        values: &["solid", "dashed", "dotted", "double", "none"],
        insert_text: "page_header_border_style:",
        description: "ページヘッダーの枠線種類を指定する",
        examples: &["<!-- kmark page_header_border_style:dashed -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_header_font_size",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_font_size:",
        description: "ページヘッダーの文字サイズを指定する",
        examples: &["<!-- kmark page_header_font_size:9pt -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_header_font_family",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_font_family:",
        description: "ページヘッダーのフォントを指定する",
        examples: &["<!-- kmark page_header_font_family:\"Yu Gothic\" -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_header_font_color",
        aliases: &[],
        param_type: "color",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_font_color:",
        description: "ページヘッダーの文字色を指定する",
        examples: &["<!-- kmark page_header_font_color:#333 -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_header_padding",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_header_padding:",
        description: "ページヘッダー文字枠の内側余白を指定する",
        examples: &["<!-- kmark page_header_padding:0.2em 0.6em -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_footer",
        aliases: &[],
        param_type: "boolean",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer:false",
        description: "ページフッターの表示を無効化する",
        examples: &["<!-- kmark page_footer:false -->"],
        priority: 89,
    },
    KmarkParamSpec {
        name: "page_footer_left",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_left:\"\"",
        description: "ページフッター左端の文字列を指定する",
        examples: &["<!-- kmark page_footer_left:\"左フッター\" -->"],
        priority: 87,
    },
    KmarkParamSpec {
        name: "page_footer_center",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_center:\"\"",
        description: "ページフッター中央の文字列を指定する",
        examples: &["<!-- kmark page_footer_center:\"中央フッター\" -->"],
        priority: 87,
    },
    KmarkParamSpec {
        name: "page_footer_right",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_right:\"\"",
        description: "ページフッター右端の文字列を指定する",
        examples: &["<!-- kmark page_footer_right:\"関係者外秘\" -->"],
        priority: 87,
    },
    KmarkParamSpec {
        name: "page_footer_opacity",
        aliases: &[],
        param_type: "number",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_opacity:",
        description: "ページフッターの透明度を0から1で指定する",
        examples: &["<!-- kmark page_footer_opacity:0.6 -->"],
        priority: 85,
    },
    KmarkParamSpec {
        name: "page_footer_offset",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_offset:",
        description: "ページ下端からフッターまでの距離を指定する",
        examples: &["<!-- kmark page_footer_offset:6mm -->"],
        priority: 85,
    },
    KmarkParamSpec {
        name: "page_footer_border_size",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_border_size:",
        description: "ページフッターの枠線太さを指定する",
        examples: &["<!-- kmark page_footer_border_size:1px -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_footer_border_color",
        aliases: &[],
        param_type: "color",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_border_color:",
        description: "ページフッターの枠線色を指定する",
        examples: &["<!-- kmark page_footer_border_color:#999 -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_footer_border_style",
        aliases: &[],
        param_type: "enum",
        contexts: &["page", "scope"],
        values: &["solid", "dashed", "dotted", "double", "none"],
        insert_text: "page_footer_border_style:",
        description: "ページフッターの枠線種類を指定する",
        examples: &["<!-- kmark page_footer_border_style:dashed -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_footer_font_size",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_font_size:",
        description: "ページフッターの文字サイズを指定する",
        examples: &["<!-- kmark page_footer_font_size:9pt -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_footer_font_family",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_font_family:",
        description: "ページフッターのフォントを指定する",
        examples: &["<!-- kmark page_footer_font_family:\"Yu Gothic\" -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_footer_font_color",
        aliases: &[],
        param_type: "color",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_font_color:",
        description: "ページフッターの文字色を指定する",
        examples: &["<!-- kmark page_footer_font_color:#333 -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_footer_padding",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_footer_padding:",
        description: "ページフッター文字枠の内側余白を指定する",
        examples: &["<!-- kmark page_footer_padding:0.2em 0.6em -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_number",
        aliases: &[],
        param_type: "enum",
        contexts: &["page", "scope"],
        values: &[
            "show",
            "hide",
            "none",
            "top-left",
            "top-center",
            "top-right",
            "bottom-left",
            "bottom-center",
            "bottom-right",
        ],
        insert_text: "page_number:",
        description: "ページ番号の表示位置を指定する",
        examples: &["<!-- kmark { page_number:bottom-center } -->"],
        priority: 90,
    },
    KmarkParamSpec {
        name: "page_number_format",
        aliases: &[],
        param_type: "string",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_format:\"{page}\"",
        description: "ページ番号の表示形式を指定する",
        examples: &["<!-- kmark { page_number_format:\"{page} / {total}\" } -->"],
        priority: 86,
    },
    KmarkParamSpec {
        name: "page_number_start",
        aliases: &[],
        param_type: "number",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_start:",
        description: "表示ページ番号の開始番号を指定する",
        examples: &["<!-- kmark { page_number_start:1 } -->"],
        priority: 84,
    },
    KmarkParamSpec {
        name: "page_number_reset",
        aliases: &[],
        param_type: "boolean",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_reset:",
        description: "このスコープからページ番号グループをリセットする",
        examples: &["<!-- kmark { page_number_reset:true } -->"],
        priority: 83,
    },
    KmarkParamSpec {
        name: "page_number_count",
        aliases: &[],
        param_type: "boolean",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_count:",
        description: "このページをページ番号カウントに含めるか指定する",
        examples: &["<!-- kmark { page_number_count:false } -->"],
        priority: 82,
    },
    KmarkParamSpec {
        name: "page_number_visible",
        aliases: &[],
        param_type: "boolean",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_visible:",
        description: "ページ番号設定を維持したまま表示有無を指定する",
        examples: &["<!-- kmark { page_number_visible:false } -->"],
        priority: 81,
    },
    KmarkParamSpec {
        name: "page_number_style",
        aliases: &[],
        param_type: "enum",
        contexts: &["page", "scope"],
        values: &[
            "decimal",
            "lower-roman",
            "upper-roman",
            "lower-alpha",
            "upper-alpha",
        ],
        insert_text: "page_number_style:",
        description: "ページ番号の表記スタイルを指定する",
        examples: &["<!-- kmark { page_number_style:lower-roman } -->"],
        priority: 80,
    },
    KmarkParamSpec {
        name: "page_number_font_size",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_font_size:",
        description: "ページ番号の文字サイズを指定する",
        examples: &["<!-- kmark { page_number_font_size:10pt } -->"],
        priority: 74,
    },
    KmarkParamSpec {
        name: "page_number_color",
        aliases: &[],
        param_type: "color",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_color:",
        description: "ページ番号の文字色を指定する",
        examples: &["<!-- kmark { page_number_color:#666 } -->"],
        priority: 73,
    },
    KmarkParamSpec {
        name: "page_number_margin_top",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_margin_top:",
        description: "ページ番号の上端距離を指定する",
        examples: &["<!-- kmark { page_number_margin_top:8mm } -->"],
        priority: 62,
    },
    KmarkParamSpec {
        name: "page_number_margin_bottom",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_margin_bottom:",
        description: "ページ番号の下端距離を指定する",
        examples: &["<!-- kmark { page_number_margin_bottom:8mm } -->"],
        priority: 62,
    },
    KmarkParamSpec {
        name: "page_number_margin_left",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_margin_left:",
        description: "ページ番号の左端距離を指定する",
        examples: &["<!-- kmark { page_number_margin_left:12mm } -->"],
        priority: 61,
    },
    KmarkParamSpec {
        name: "page_number_margin_right",
        aliases: &[],
        param_type: "length",
        contexts: &["page", "scope"],
        values: &[],
        insert_text: "page_number_margin_right:",
        description: "ページ番号の右端距離を指定する",
        examples: &["<!-- kmark { page_number_margin_right:12mm } -->"],
        priority: 61,
    },
    KmarkParamSpec {
        name: "define",
        aliases: &[],
        param_type: "identifier",
        contexts: &["single", "scope", "page"],
        values: &[],
        insert_text: "define:",
        description: "現在のパラメータセットに名前を付ける",
        examples: &["<!-- kmark define:image_large w:300 h:200 -->"],
        priority: 65,
    },
    KmarkParamSpec {
        name: "use",
        aliases: &[],
        param_type: "identifier",
        contexts: &["single", "scope", "page"],
        values: &[],
        insert_text: "use:",
        description: "定義済みのパラメータセットを使用する",
        examples: &["<!-- kmark use:image_large -->"],
        priority: 90,
    },
];

pub fn kmark_param_schema_json() -> String {
    let mut output = String::new();
    output.push_str("{\n");
    writeln!(output, "  \"schemaVersion\": {KMARK_PARAM_SCHEMA_VERSION},")
        .expect("schema json write failed");
    output.push_str("  \"params\": [\n");

    for (index, spec) in KMARK_PARAM_SPECS.iter().enumerate() {
        write_param_spec_json(&mut output, spec);

        if index + 1 < KMARK_PARAM_SPECS.len() {
            output.push_str(",");
        }

        output.push_str("\n");
    }

    output.push_str("  ]\n");
    output.push_str("}\n");
    output
}

fn write_param_spec_json(output: &mut String, spec: &KmarkParamSpec) {
    output.push_str("    {\n");
    write_string_field(output, 6, "name", spec.name, true);
    write_string_array_field(output, 6, "aliases", spec.aliases, true);
    write_string_field(output, 6, "type", spec.param_type, true);
    write_string_array_field(output, 6, "contexts", spec.contexts, true);

    if !spec.values.is_empty() {
        write_string_array_field(output, 6, "values", spec.values, true);
    }

    write_string_field(output, 6, "insertText", spec.insert_text, true);
    write_string_field(output, 6, "description", spec.description, true);
    write_string_array_field(output, 6, "examples", spec.examples, true);
    writeln!(output, "      \"priority\": {}", spec.priority).expect("schema json write failed");
    output.push_str("    }");
}

fn write_string_field(
    output: &mut String,
    indent: usize,
    key: &str,
    value: &str,
    trailing_comma: bool,
) {
    write_indent(output, indent);
    push_json_string(output, key);
    output.push_str(": ");
    push_json_string(output, value);

    if trailing_comma {
        output.push_str(",");
    }

    output.push_str("\n");
}

fn write_string_array_field(
    output: &mut String,
    indent: usize,
    key: &str,
    values: &[&str],
    trailing_comma: bool,
) {
    write_indent(output, indent);
    push_json_string(output, key);
    output.push_str(": [");

    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            output.push_str(", ");
        }

        push_json_string(output, value);
    }

    output.push_str("]");

    if trailing_comma {
        output.push_str(",");
    }

    output.push_str("\n");
}

fn write_indent(output: &mut String, indent: usize) {
    for _ in 0..indent {
        output.push(' ');
    }
}

fn push_json_string(output: &mut String, value: &str) {
    output.push('"');

    for character in value.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            character if character.is_control() => {
                write!(output, "\\u{:04x}", character as u32).expect("schema json write failed");
            }
            character => output.push(character),
        }
    }

    output.push('"');
}

#[cfg(test)]
mod tests {
    use super::kmark_param_schema_json;

    #[test]
    fn generated_frontend_schema_is_in_sync() {
        let frontend_schema =
            include_str!("../../../src/features/kmark-completion/schema/kmark-param-schema.json");

        assert_eq!(
            frontend_schema.replace("\r\n", "\n"),
            kmark_param_schema_json()
        );
    }
}
