import { type KmarkParamSpec } from "../core/types";

export const KMARK_PARAM_SPECS: readonly KmarkParamSpec[] = [
  {
    name: "align",
    type: "enum",
    contexts: ["single", "scope", "text", "image"],
    values: ["left", "center", "right"],
    insertText: "align:",
    description: "対象ブロックの横方向配置を指定する",
    examples: ["<!-- kmark align:right -->"],
    priority: 100,
  },
  {
    name: "valign",
    type: "enum",
    contexts: ["single", "scope", "text", "image"],
    values: ["top", "center", "bottom", "stretch"],
    insertText: "valign:",
    description: "対象ブロックの縦方向配置を指定する",
    examples: ["<!-- kmark valign:top -->"],
    priority: 70,
  },
  {
    name: "w",
    aliases: ["width"],
    type: "length",
    contexts: ["single", "image", "shape"],
    insertText: "w:",
    description: "対象要素の幅を指定する",
    examples: ["<!-- kmark w:200 -->", "<!-- kmark w:50% -->"],
    priority: 95,
  },
  {
    name: "h",
    aliases: ["height"],
    type: "length",
    contexts: ["single", "image", "shape"],
    insertText: "h:",
    description: "対象要素の高さを指定する",
    examples: ["<!-- kmark h:100 -->"],
    priority: 95,
  },
  {
    name: "fit",
    type: "enum",
    contexts: ["image", "single"],
    values: ["contain", "cover", "fill", "none", "scale-down"],
    insertText: "fit:",
    description: "画像や要素の収まり方を指定する",
    examples: ["<!-- kmark fit:contain -->"],
    priority: 90,
  },
  {
    name: "pos",
    type: "enum",
    contexts: ["single", "image"],
    values: ["center", "top", "bottom", "left", "right", "top_left", "top_right", "bottom_left", "bottom_right"],
    insertText: "pos:",
    description: "画像や要素内の表示位置を指定する",
    examples: ["<!-- kmark pos:top_left -->"],
    priority: 70,
  },
  {
    name: "border_size",
    type: "length",
    contexts: ["single", "image", "scope", "shape"],
    insertText: "border_size:",
    description: "枠線の太さを指定する",
    examples: ["<!-- kmark border_size:2 -->"],
    priority: 80,
  },
  {
    name: "border_color",
    type: "color",
    contexts: ["single", "image", "scope", "shape"],
    insertText: "border_color:",
    description: "枠線の色を指定する",
    examples: ["<!-- kmark border_color:red -->", "<!-- kmark border_color:#ff0000 -->"],
    priority: 80,
  },
  {
    name: "border_style",
    type: "enum",
    contexts: ["single", "image", "scope", "shape"],
    values: ["solid", "dashed", "dotted", "double", "none"],
    insertText: "border_style:",
    description: "枠線の種類を指定する",
    examples: ["<!-- kmark border_style:dashed -->"],
    priority: 75,
  },
  {
    name: "layout",
    type: "enum",
    contexts: ["scope"],
    values: ["row", "column"],
    insertText: "layout:",
    description: "スコープ内の要素配置を指定する",
    examples: ["<!-- kmark { layout:row } -->"],
    priority: 100,
  },
  {
    name: "gap",
    type: "length",
    contexts: ["scope"],
    insertText: "gap:",
    description: "スコープ内の要素間隔を指定する",
    examples: ["<!-- kmark { layout:row gap:8 } -->"],
    priority: 85,
  },
  {
    name: "wrap",
    type: "boolean",
    contexts: ["scope"],
    insertText: "wrap:",
    description: "横並び要素の折り返しを有効にする",
    examples: ["<!-- kmark { layout:row wrap:true } -->"],
    priority: 80,
  },
  {
    name: "page_size",
    type: "enum",
    contexts: ["page", "scope"],
    values: ["A3", "A4", "A5", "B4", "B5", "Letter", "Legal", "custom"],
    insertText: "page_size:",
    description: "ページサイズを指定する",
    examples: ["<!-- kmark { page_size:A4 } -->"],
    priority: 100,
  },
  {
    name: "orientation",
    aliases: ["page_orientation"],
    type: "enum",
    contexts: ["page", "scope"],
    values: ["portrait", "landscape"],
    insertText: "orientation:",
    description: "ページの向きを指定する",
    examples: ["<!-- kmark { orientation:landscape } -->"],
    priority: 95,
  },
  {
    name: "page_width",
    type: "length",
    contexts: ["page", "scope"],
    insertText: "page_width:",
    description: "customページの幅を指定する",
    examples: ["<!-- kmark { page_size:custom page_width:210mm } -->"],
    priority: 60,
  },
  {
    name: "page_height",
    type: "length",
    contexts: ["page", "scope"],
    insertText: "page_height:",
    description: "customページの高さを指定する",
    examples: ["<!-- kmark { page_size:custom page_height:297mm } -->"],
    priority: 60,
  },
  {
    name: "font_size",
    type: "length",
    contexts: ["page", "scope"],
    insertText: "font_size:",
    description: "用紙表示の文字サイズを指定する",
    examples: ["<!-- kmark { font_size:12pt } -->"],
    priority: 80,
  },
  {
    name: "margin",
    aliases: ["page_margin"],
    type: "length",
    contexts: ["page", "scope"],
    insertText: "margin:",
    description: "用紙表示の余白を指定する",
    examples: ["<!-- kmark { margin:10mm } -->"],
    priority: 75,
  },
  {
    name: "page_margin_top",
    type: "length",
    contexts: ["page", "scope"],
    insertText: "page_margin_top:",
    description: "用紙表示の上余白を指定する",
    examples: ["<!-- kmark { page_margin_top:10mm } -->"],
    priority: 55,
  },
  {
    name: "page_margin_right",
    type: "length",
    contexts: ["page", "scope"],
    insertText: "page_margin_right:",
    description: "用紙表示の右余白を指定する",
    examples: ["<!-- kmark { page_margin_right:10mm } -->"],
    priority: 55,
  },
  {
    name: "page_margin_bottom",
    type: "length",
    contexts: ["page", "scope"],
    insertText: "page_margin_bottom:",
    description: "用紙表示の下余白を指定する",
    examples: ["<!-- kmark { page_margin_bottom:10mm } -->"],
    priority: 55,
  },
  {
    name: "page_margin_left",
    type: "length",
    contexts: ["page", "scope"],
    insertText: "page_margin_left:",
    description: "用紙表示の左余白を指定する",
    examples: ["<!-- kmark { page_margin_left:10mm } -->"],
    priority: 55,
  },
  {
    name: "define",
    type: "identifier",
    contexts: ["single", "scope", "page"],
    insertText: "define:",
    description: "現在のパラメータセットに名前を付ける",
    examples: ["<!-- kmark define:image_large w:300 h:200 -->"],
    priority: 65,
  },
  {
    name: "use",
    type: "identifier",
    contexts: ["single", "scope", "page"],
    insertText: "use:",
    description: "定義済みのパラメータセットを使用する",
    examples: ["<!-- kmark use:image_large -->"],
    priority: 90,
  },
] as const;
