import { type KmarkSnippetSpec } from "../core/types";

export const KMARK_SNIPPET_SPECS: readonly KmarkSnippetSpec[] = [
  {
    label: "align right",
    description: "対象ブロックを右寄せにする",
    contexts: ["single"],
    insertText: "align:right",
    priority: 100,
  },
  {
    label: "align center",
    description: "対象ブロックを中央寄せにする",
    contexts: ["single"],
    insertText: "align:center",
    priority: 95,
  },
  {
    label: "image size",
    description: "画像の幅・高さを指定する",
    contexts: ["image", "single"],
    insertText: "w:${1:200} h:${2:100}",
    priority: 100,
  },
  {
    label: "image width",
    description: "画像幅だけを指定する",
    contexts: ["image", "single"],
    insertText: "w:${1:300}",
    priority: 95,
  },
  {
    label: "image border",
    description: "画像に枠線を付ける",
    contexts: ["image", "single"],
    insertText: "border_size:${1:2} border_color:${2:#000000} border_style:${3:solid}",
    priority: 90,
  },
  {
    label: "scope row",
    description: "横並びスコープを作成する",
    contexts: ["scope"],
    insertText: "{ layout:row gap:${1:8} wrap:${2:true} }",
    priority: 100,
  },
  {
    label: "scope column",
    description: "縦並びスコープを作成する",
    contexts: ["scope"],
    insertText: "{ layout:column gap:${1:8} }",
    priority: 95,
  },
  {
    label: "page A4 vertical",
    description: "A4縦ページ設定を作成する",
    contexts: ["page", "scope"],
    insertText: "{ page_size:A4 page_direction:vertical page_font_size:${1:12pt} page_margin:${2:20mm} }",
    priority: 100,
  },
  {
    label: "page A4 horizontal",
    description: "A4横ページ設定を作成する",
    contexts: ["page", "scope"],
    insertText: "{ page_size:A4 page_direction:horizontal page_font_size:${1:12pt} page_margin:${2:15mm} }",
    priority: 100,
  },
  {
    label: "toc",
    description: "現在位置以降の見出しから目次を作成する",
    contexts: ["toc", "single"],
    insertText: "toc:true toc_depth:${1:6}",
    priority: 100,
  },
  {
    label: "heading number",
    description: "スコープ内の見出しへ階層番号を表示する",
    contexts: ["scope", "single"],
    insertText: "heading_number:true heading_number_from:${1:2} heading_number_depth:${2:3} heading_number_pattern:${3|dot,dot_trailing,hyphen,chapter|}",
    priority: 98,
  },
  {
    label: "table compact",
    description: "表セル余白と文字詰めを指定する",
    contexts: ["table", "single"],
    insertText: "table_cell_padding_x:${1:1mm} table_cell_padding_y:${2:0.3mm} line_height:${3:1.05} font_size:${4:8.5pt} table_fit:${5:auto}",
    priority: 100,
  },
  {
    label: "use style",
    description: "定義済みスタイルを使用する",
    contexts: ["single", "scope", "page"],
    insertText: "use:${1:style_name}",
    priority: 90,
  },
] as const;
